### ISSUE TITLE
Where is the old code?

### ISSUE THREAD

**Issue by pviolette3** [gt-webdev/ccorgs#4]
i like to use it as an example of working with authentication / mongo.

**Comment by thedekel** [comment]
to answer your question: https://github.com/gt-webdev/attendance

and to give general advice: don't use what we did in ccorgsV1 for authentication and for mongo (mongoose is bad). 

I'd recommend using passport or everyauth as an authentication library. Both are pretty similar, but I believe that passport has better express3 support. And you really wouldn't be making the most out of mongo if you're using mongoose (which is what we used in ccorgsV1) since it's basically ignoring the greatest advantage of a schema-less database and makes your mongo behave more like SQL. I'd suggest either using postgreSQL since it's probably the best freely available SQL DBMS for you to use, or just using mongodb with the native library (which would require you to learn a bit of mongo).

If you're interested in authentication for the purpose of learning how it works by implementing it yourself, let me know and I'll point you in better direction than the silly code that we hacked together 2 years ago for ccorgs.

:poop:
